---
title: "Untitled"
author: "Priscilla Hare"
date: "5/31/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
mc_data <- read_csv('HW4Data.csv')
```

```{r}
a <- lm(MC_A ~ Abatement, data = mc_data)
b <- lm(MC_B ~ Abatement, data = mc_data)
c <- lm(MC_C ~ Abatement, data = mc_data)
d <- lm(MC_D ~ Abatement, data = mc_data)

```

```{r}

mc_data <- mc_data %>% 
  mutate(MC_C_sq = MC_C*MC_C) %>% 
  mutate(MC_D_sq = MC_D*MC_D) %>% 
  mutate(MC_D_exp = exp(MC_D))

```

```{r}
#example of quadratic model:
c_sq <- lm(Abatement ~ MC_C + MC_C_sq, data = mc_data)

d_sq <- lm(Abatement ~ MC_D + MC_D_sq, data = mc_data) #use linear


```

```{r}

ggplot(mc_data) +
  geom_point(aes(Abatement, MC_A)) +
  geom_smooth(aes(Abatement, MC_A), method = lm)

```

Question 2: Finding Demand
```{r}
#Sector A

# MC = Int + MC_A*X 

cp_A <- 180

MC_A_cp <- a$coefficients[1] + a$coefficients[2] * cp_A

D_slope_A <- (MC_A_cp/(-cp_A))

demand_A <- function(x){MC_A_cp + D_slope_A * x}

supply_A <- function(x){a$coefficients[1] + a$coefficients[2] * x}

 

```

```{r}
#Sector B

# MC = Int + MC_B*X 

cp_B <- 200

MC_B_cp <- b$coefficients[1] + b$coefficients[2] * cp_B

D_slope_B <- (MC_B_cp/(-cp_B))

supply_B <- function(x){b$coefficients[1] + b$coefficients[2] * x}

# so demand for B = MC_B_cp + D_slope_B * X
```

```{r}
#Sector C

# MC = Int + MC_C*X 

cp_C <- 220

MC_C_cp <- c$coefficients[1] + c$coefficients[2] * cp_C

D_slope_C <- (MC_C_cp/(-cp_C))

supply_C <- function(x){c$coefficients[1] + c$coefficients[2] * x}



# so demand for C = MC_C_cp + D_slope_C * X
```


```{r}
#Sector D

# MC = Int + MC_D*X 

cp_D <- 300

MC_D_cp <- d$coefficients[1] + d$coefficients[2] * cp_D

D_slope_D <- (MC_D_cp/(-cp_D))

supply_D <- function(x){d$coefficients[1] + d$coefficients[2] * x}

# so demand for D = MC_D_CP + D_slope_D * X
```

#Part 3
a) Cap on carbon: each sector cut by 100
```{r}
# sector A: 180 to 80
# sector B; 200 to 100
# sector C; 220 to 120

TC_A_cap <- integrate(supply_A, 0, 100)
TC_B_cap <- integrate(supply_B, 0, 100)
TC_C_cap <- integrate(supply_C, 0, 100)

TC_A_cap$value # 2019.762
TC_B_cap$value # 1925.491
TC_C_cap$value # 2753.63

TC_country_cap <- TC_A_cap$value + TC_B_cap$value + TC_C_cap$value

TC_country_cap # 6698.883

# no tax revenue generated

```
b) Tax on carbon
```{r}
# first rearrange supply curves


A_rearrange <- function(y){(1/a$coefficients[2])*(-a$coefficients[1] + y)}

B_rearrange <- function(y){(1/b$coefficients[2])*(-b$coefficients[1] + y)}

C_rearrange <- function(y){(1/c$coefficients[2])*(-c$coefficients[1] + y)}

#ag_supply_country_X2 <- function(y){A_rearrange(y) + B_rearrange(y) + C_rearrange(y)}

ag_intercept <- (-a$coefficients[1]/a$coefficients[2]) + (-b$coefficients[1]/b$coefficients[2]) + (-c$coefficients[1]/c$coefficients[2])

ag_slope <- (1/a$coefficients[2]) + (1/b$coefficients[2]) + (1/c$coefficients[2])

ag_supply_country_X <- function(x){(-ag_intercept/ag_slope) + (x/ag_slope)}

taxprice <- ag_supply_country_X(300)

A_rearrange(taxprice) + B_rearrange(taxprice) + C_rearrange(taxprice)

A_abate <- A_rearrange(taxprice) # 83.33489 
B_abate <- B_rearrange(taxprice) # 151.4956
C_abate <- C_rearrange(taxprice) # 65.16953 

A_tax_abatementcost <- integrate(supply_A, lower = 0, upper = A_abate) 

TC_A_tax <- A_tax_abatementcost$value + (cp_A - A_abate)*taxprice   
#  5093.786 

B_tax_abatementcost <- integrate(supply_B, lower = 0, upper = B_abate) 

TC_B_tax <- B_tax_abatementcost$value + (cp_B - B_abate)*taxprice   
#  5604.635 

C_tax_abatementcost <- integrate(supply_C, lower = 0, upper = C_abate) 

TC_C_tax <- C_tax_abatementcost$value + (cp_C - C_abate)*taxprice   
#  7009.365  

TC_country_tax <- TC_C_tax + TC_B_tax + TC_A_tax
#  17707.79

#tax revenue generated

tax_rev <- (cp_A - A_abate)*taxprice + (cp_B - B_abate)*taxprice  + (cp_C - C_abate)*taxprice 
#  11827.97 

```

c) cap and trade
```{r}

TC_A_captrade <- A_tax_abatementcost$value + (100 - A_abate)*taxprice
# 1939.66

TC_B_captrade <- B_tax_abatementcost$value + (100 - B_abate)*taxprice
#  1661.977

TC_C_captrade <- C_tax_abatementcost$value + (100 - C_abate)*taxprice
#  2278.176 

TC_country_captrade <- TC_A_captrade + TC_B_captrade + TC_C_captrade
#  5879.812 

# no tax revenue

```

# part 4
```{r}

```

```{r}
# first rearrange supply curves


A_rearrange <- function(y){(1/a$coefficients[2])*(-a$coefficients[1] + y)}

B_rearrange <- function(y){(1/b$coefficients[2])*(-b$coefficients[1] + y)}

C_rearrange <- function(y){(1/c$coefficients[2])*(-c$coefficients[1] + y)}

D_rearrange <- function(y){(1/d$coefficients[2])*(-d$coefficients[1] + y)}

#ag_supply_country_X2 <- function(y){A_rearrange(y) + B_rearrange(y) + C_rearrange(y)}

ag_intercept_inter <- (-a$coefficients[1]/a$coefficients[2]) + (-b$coefficients[1]/b$coefficients[2]) + (-c$coefficients[1]/c$coefficients[2]) + (-d$coefficients[1]/d$coefficients[2])

ag_slope_inter <- (1/a$coefficients[2]) + (1/b$coefficients[2]) + (1/c$coefficients[2]) + (1/d$coefficients[2])

ag_supply_country_X_Y <- function(x){(-ag_intercept_inter/ag_slope_inter) + (x/ag_slope_inter)}

taxprice_inter <- ag_supply_country_X_Y(300)

A_rearrange(taxprice_inter) + B_rearrange(taxprice_inter) + C_rearrange(taxprice_inter) + D_rearrange(taxprice_inter)

A_abate_inter <- A_rearrange(taxprice_inter) # 66.65079 
B_abate_inter <- B_rearrange(taxprice_inter) # 103.0711
C_abate_inter <- C_rearrange(taxprice_inter) #  52.89119  
D_abate_inter <- D_rearrange(taxprice_inter) # 77.3869 


A_tax_abatementcost_inter <- integrate(supply_A, lower = 0, upper = A_abate_inter) 

#TC_A_tax_inter <- A_tax_abatementcost_inter$value + (cp_A - A_abate_inter)*taxprice_inter  
#  4083.188 

B_tax_abatementcost_inter <- integrate(supply_B, lower = 0, upper = B_abate_inter) 

#TC_B_tax_inter <- B_tax_abatementcost_inter$value + (cp_B - B_abate_inter)*taxprice_inter   
#  4904.803 

C_tax_abatementcost_inter <- integrate(supply_C, lower = 0, upper = C_abate_inter) 

#TC_C_tax_inter <- C_tax_abatementcost_inter$value + (cp_C - C_abate_inter)*taxprice_inter   
#   5460.18 

#TC_country_X_tax_inter <- TC_C_tax_inter + TC_B_tax_inter + TC_A_tax_inter
#   14448.17 

D_abatementcost_inter <- integrate(supply_D, lower = 0, upper = D_abate_inter) 



```


```{r}

TC_A_captrade_inter <- A_tax_abatementcost_inter$value + (100 - A_abate_inter)*taxprice_inter
#  1698.989 

TC_B_captrade_inter <- B_tax_abatementcost_inter$value + (100 - B_abate_inter)*taxprice_inter
#  1924.554 

TC_C_captrade_inter <- C_tax_abatementcost_inter$value + (100 - C_abate_inter)*taxprice_inter
# 1883.88 

TC_D_captrade_inter <- D_abatementcost_inter$value + (0 - D_abate_inter)*taxprice_inter
# -778.3183 


TC_country_X_captradeinter <- TC_A_captrade_inter + TC_B_captrade_inter + TC_C_captrade_inter
#  5507.423 
# the value for country x is a lower cost then under cap and trade for just their country

# no tax revenue
```

5b
```{r}

A_emissions <- cp_A - A_abate_inter
B_emissions <- cp_B - B_abate_inter
C_emissions <- cp_C - C_abate_inter

X_emissions <-A_emissions + B_emissions + C_emissions
#  377.3869 
Y_emissions <- 300 - D_abate_inter
#  222.6131 

```

5c
```{r}

```

